stages:          # List of stages for jobs, and their order of execution
  - build
  - lint_format
  - migrations
  - tests
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .

Lint:
  stage: lint_format
  script:
    - docker run --rm --network MyNetwork booking-api-image ruff check

Format:
  stage: lint_format
  script:
    - docker run --rm --network MyNetwork booking-api-image ruff format --check

Migrations:
  stage: migrations
  script:
    - docker run --rm --network MyNetwork booking-api-image alembic upgrade head

Test:
  stage: tests
  script:
    - docker run --rm --network MyNetwork booking-api-image pytest -s -v

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec booking_nginx nginx -s reload
