services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    ports:
      - '7777:8000'
    networks:
      - MyNetwork
    env_file:
      - .env
    volumes:
      - ./src/static/images:/app/src/static/images

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - MyNetwork
    env_file:
      - .env
    command: celery --app=src.tasks.celery_app:celery_instance worker -l INFO


  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - MyNetwork
    env_file:
      - .env
    command: celery --app=src.tasks.celery_app:celery_instance beat -l INFO

networks:
  MyNetwork:
    external: true